config/routes.rb
Rails.application.routes.draw do
  root to: "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    def index
        @kittens = Kitten.all

        respond_to do |format|
            format.json { render json: @kittens }
        end
    end

    def show
        set_kitten

        respond_to do |format|
            format.json { render json: @kitten }
        end
    end

    def new
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.new(kitten_params)

        if @kitten.save
            flash[:success] = "Kitten created!"
            redirect_to @kitten
        else
            flash[:error] = "Whoops! There was an error creating your kitten!"
            render :new
        end
    end

    def edit
        set_kitten
    end

    def update
        set_kitten

        if @kitten.update(kitten_params)
            flash[:success] = "Kitten updated!"
            redirect_to @kitten
        else
            flash[:error] = "Whoops! There was an error updating your kitten!"
            render :edit
        end
    end

    def destroy
        set_kitten

        if @kitten.destroy
            flash[:success] = "Kitten deleted!"
            redirect_to root_path
        else
            flash[:error] = "Whoops! There was an error deleting your kitten!"
            redirect_to @kitten
        end
    end


    private

    def set_kitten
        @kitten = Kitten.find(params[:id])
    end

    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten, local: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.number_field :age %>

    <%= f.label :softness %>
    <%= f.number_field :softness, in: 1.0..10.0 %>

    <%= f.label :cuteness %>
    <%= f.number_field :cuteness, in: 1.0..10.0 %>
    
    <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render "form" %>

<%=  link_to "Delete Kitten", @kitten, method: :delete, data: { confirm: "Really delete this kitten?" } %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<ul>
    <% @kittens.each do |kitten| %>
        <li><%= link_to kitten.name, kitten %></li>
        <%=  link_to "Delete Kitten", @kitten, method: :delete, data: { confirm: "Really delete this kitten?" } %>
    <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render "form" %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<h3>Age: <%= @kitten.age %></h3>
<h3>Cuteness: <%= @kitten.cuteness %></h3>
<h3>Softness: <%= @kitten.softness %></h3>

<%= link_to "Edit Kitten", edit_kitten_path(@kitten) %>
<%=  link_to "Delete Kitten", @kitten, method: :delete, data: { confirm: "Really delete this kitten?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:success] %>
      <%= flash[:success] %>
    <% end %>
    <% if flash[:error] %>
      <%= flash[:error] %>
    <% end %>
    <%= yield %>
  </body>
</html>